twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        no_image: '/img/image.png'
        dt_format: 'd/m/Y H:i'

when@test:
    twig:
        strict_variables: true
